### PR TITLE
Explosion effect feature

### PR DESCRIPTION
**Pull request by frangauthier**
I finished my work.

### CODE REVIEW

**Comment by MatSki02** [comment]
nah b code sucks

**Review by MatSki02 — APPROVED** [review]
Sacha loves men so post it its ok.

**Comment by SachaPaquette** [comment]
mmm mateusz in yeezys

**Review by LoukaM — APPROVED** [review]
Very good reviews

**Review by SachaPaquette — APPROVED** [review]
grrrr woof woof

**Review by WilliamAndrews1013 — APPROVED** [review]

**Review by LoukaM — APPROVED** [review]
ban Matski

**Review by MatSki02 — APPROVED** [review]
CAp no sheesh noice ez I need help

**Review by MatSki02 — APPROVED** [review]
.

**Review by LoukaM — APPROVED** [review]

**Review by MatSki02 — APPROVED** [review]
sure

**Comment by SachaPaquette** [comment]
Petition to kick Mateusz and Louka => dead weights

**Review by LoukaM — APPROVED** [review]

**Pull request merged**
